use lib_ruby_parser_nodes::template::*;

const TEMPLATE: &str = "// This file is autogenerated by {{ helper generated-by }}

class DiagnsoticMessage {}
const messages = {};

(function() {

{{ each message }}<dnl>
class {{ helper message-camelcase-name }} extends DiagnsoticMessage {
    constructor(
{{ each message-field }}<dnl>
        {{ helper message-field-js-name }},
{{ end }}<dnl>
    ) {
        super();
{{ each message-field }}<dnl>
        this.{{ helper message-field-js-name }} = {{ helper message-field-js-name }};
{{ end }}<dnl>
    }
}
messages.{{ helper message-camelcase-name }} = {{ helper message-camelcase-name }};
{{ end }}<dnl>

})();

root.DiagnsoticMessage = DiagnsoticMessage;
root.messages = messages;
";

pub(crate) fn codegen() {
    let template = TemplateRoot::new(TEMPLATE).unwrap();
    let fns = crate::codegen::fns::default_fns!();

    let contents = template.render(ALL_DATA, &fns);
    std::fs::write("../js/messages.js", contents).unwrap();
}
